### ISSUE TITLE
Big image maps won't render

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#2]
With this command:

java -jar BlockMap.jar render /home/minecraft/server/bukkit/empire/region  --create-big-image --min-X=-5 --max-X=4 --min-Z=-5 --max-Z=4 -o /home/minecraft/server/maps/empire/png

I get the following:

`18-11-09 15:02:21:711 DEBUG RegionRenderer [112] - Dimension: 542208, 101376
18-11-09 15:02:21:711 ERROR RegionRenderer [117] - Could not create image, is it too big?
java.lang.NegativeArraySizeException: null
        at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75) ~[?:1.8.0_191]
        at java.awt.image.Raster.createPackedRaster(Raster.java:467) ~[?:1.8.0_191]
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032) ~[?:1.8.0_191]
        at java.awt.image.BufferedImage.<init>(BufferedImage.java:333) ~[?:1.8.0_191]
        at de.piegames.blockmap.standalone.PostProcessing.createBigImage(PostProcessing.java:115) [BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:166) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:858) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.access$700(CommandLine.java:104) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1035) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1003) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:911) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1194) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.parseWithHandler(CommandLine.java:1133) [BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:202) [BlockMap-1.1.1.jar:?]
18-11-09 15:02:21:714 INFO  RegionRenderer [173] - Done. Region files rendered/skipped/failed/total: 202/0/0/202
`
the image is def. not too big to be rendered, IT should be 4kx4k pixels, 1.4 MB. I wonder why the dimensions are given as 542208, 101376

**Comment by uncovery** [comment]
Nevermind, realized that I need block coordinates instead of chunks. Will check again.
