### ISSUE TITLE
issues with running on mac os x

### ISSUE THREAD

**Issue by rkiddy** [Minecraft-Technik-Wiki/BlockMap#23]
Any suggestions?

     $ java -version
     java version "1.8.0_131"
     Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
     Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
     $ 
     $ java -jar BlockMap-1.3.0.jar 
     Error: A JNI error has occurred, please check your installation and try again
     Exception in thread "main" java.lang.UnsupportedClassVersionError: de/piegames/blockmap/standalone/CommandLineMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
     	at java.lang.ClassLoader.defineClass1(Native Method)
     	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
     	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
     	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
     	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
     	at java.security.AccessController.doPrivileged(Native Method)
     	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
     	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
     	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

* Used brew to install java, which gave me java 12:
```
     $ java -version
     openjdk version "12.0.1" 2019-04-16
     OpenJDK Runtime Environment (build 12.0.1+12)
     OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
     
     $ java -jar BlockMap-1.3.0.jar 
     WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
     Graphics Device initialization failed for :  es2, sw
     Error initializing QuantumRenderer: no suitable pipeline found
     java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
     	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
     	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
     	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
     	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
     	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
     	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
     	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
     	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
     	at java.base/java.lang.Thread.run(Thread.java:835)
     Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
     	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
     	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
     	... 1 more
     19-05-12 16:37:42:475 FATAL RegionRenderer [256] - Could not load GUI main class
     java.lang.reflect.InvocationTargetException: null
     	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
     	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
     	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
     	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
     	at de.piegames.blockmap.standalone.CommandLineMain.run(CommandLineMain.java:249) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine.execute(CommandLine.java:1043) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine.access$900(CommandLine.java:142) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405) [BlockMap-1.3.0.jar:?]
     	at picocli.CommandLine.parseWithHandler(CommandLine.java:1344) [BlockMap-1.3.0.jar:?]
     	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:265) [BlockMap-1.3.0.jar:?]
     Caused by: java.lang.RuntimeException: No toolkit found
     	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) ~[BlockMap-1.3.0.jar:?]
     	at java.lang.Thread.run(Thread.java:835) ~[?:?]
```
* downloaded JavaFX 12 from https://openjfx.io/
```
     $ export FX12=/Users/ray/Projects/javafx-sdk-11.0.2/lib
     
     $ java --module-path $FX12 --add-modules javafx.controls -jar BlockMap-1.3.0.jar 
     WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
     19-05-12 17:09:08:386 FATAL GuiMain [46] - Cannot start BlockMap
     java.lang.IllegalAccessError: class com.sun.javafx.fxml.FXMLLoaderHelper (in unnamed module @0x298a30df) cannot access class com.sun.javafx.util.Utils (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.util to unnamed module @0x298a30df
     	at com.sun.javafx.fxml.FXMLLoaderHelper.<clinit>(FXMLLoaderHelper.java:38) ~[BlockMap-1.3.0.jar:?]
     	at javafx.fxml.FXMLLoader.<clinit>(FXMLLoader.java:2056) ~[BlockMap-1.3.0.jar:?]
     	at de.piegames.blockmap.guistandalone.GuiMain.start(GuiMain.java:34) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics.jar:?]
     	at java.security.AccessController.doPrivileged(AccessController.java:389) ~[?:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics.jar:?]
     	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) [javafx.graphics.jar:?]
     
     $ java --module-path $FX12 --add-modules javafx.controls,javafx.fxml -jar BlockMap-1.3.0.jar 
     WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
     19-05-12 17:10:04:655 FATAL GuiMain [46] - Cannot start BlockMap
     java.lang.IllegalAccessError: superclass access check failed: class impl.org.controlsfx.behavior.RangeSliderBehavior (in unnamed module @0xa1d113b) cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0xa1d113b
     	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
     	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
     	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
     	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802) ~[?:?]
     	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700) ~[?:?]
     	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623) ~[?:?]
     	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
     	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
     	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
     	at impl.org.controlsfx.skin.RangeSliderSkin.<init>(RangeSliderSkin.java:95) ~[BlockMap-1.3.0.jar:?]
     	at org.controlsfx.control.RangeSlider.createDefaultSkin(RangeSlider.java:194) ~[BlockMap-1.3.0.jar:?]
     	at javafx.scene.control.Control.doProcessCSS(Control.java:897) ~[javafx.controls.jar:?]
     	at javafx.scene.control.Control.access$000(Control.java:83) ~[javafx.controls.jar:?]
     	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89) ~[javafx.controls.jar:?]
     	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67) ~[javafx.controls.jar:?]
     	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.doProcessCSS(Parent.java:1397) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.access$400(Parent.java:79) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.doProcessCSS(Parent.java:1397) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.access$400(Parent.java:79) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.doProcessCSS(Parent.java:1397) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent.access$400(Parent.java:79) ~[javafx.graphics.jar:?]
     	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145) ~[javafx.graphics.jar:?]
     	at javafx.scene.Node.processCSS(Node.java:9529) ~[javafx.graphics.jar:?]
     	at javafx.scene.Scene.doCSSPass(Scene.java:569) ~[javafx.graphics.jar:?]
     	at javafx.scene.Scene.preferredSize(Scene.java:1745) ~[javafx.graphics.jar:?]
     	at javafx.scene.Scene$2.preferredSize(Scene.java:393) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66) ~[javafx.graphics.jar:?]
     	at javafx.stage.Window$12.invalidated(Window.java:1086) ~[javafx.graphics.jar:?]
     	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110) ~[javafx.base.jar:?]
     	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145) ~[javafx.base.jar:?]
     	at javafx.stage.Window.setShowing(Window.java:1174) ~[javafx.graphics.jar:?]
     	at javafx.stage.Window.show(Window.java:1189) ~[javafx.graphics.jar:?]
     	at javafx.stage.Stage.show(Stage.java:273) ~[javafx.graphics.jar:?]
     	at de.piegames.blockmap.guistandalone.GuiMain.start(GuiMain.java:41) ~[BlockMap-1.3.0.jar:?]
     	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx.graphics.jar:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics.jar:?]
     	at java.security.AccessController.doPrivileged(AccessController.java:389) ~[?:?]
     	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics.jar:?]
     	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) [javafx.graphics.jar:?]
     
```

**Comment by saibotk** [comment]
Yes since the new version java 11+ is required to run blockmap. It seems like you have installed java 8 instead.
When using Java 11 it should work fine, otherwise feel free to report any further issues.

**Comment by rkiddy** [comment]
When I first tried to launch this version, I did have only java 8. I installed java 12. But there seemed (as I think I see in the output above) that there is then a problem with the graphics or UI layer. Or so it seemed to me. But then I installed a later version of JavaFX and tried to launch with it, but that did not work.

I will investigate further when I can. Hopefully I can find some info that you will be able to put into the README to get anyone else get past the issue.

thanx

**Comment by piegamesde** [comment]
There should be no need to install JavaFX, since it comes bundled with the application now. The issue with `impl.org.controlsfx.behavior.RangeSliderBehavior` is a [known bug in ControlsFX](https://github.com/controlsfx/controlsfx/issues/993) (but there are more problems in those stack traces than that one).

Please try to run BlockMap under Java 11, and I'll try to get Java 12 working on my machine. Also, could you please test if it runs from Gradle? (Task `run2` does the same thing as `run`, but has a workaround against the said ControlsFX bug)

    git clone https://github.com/Minecraft-Technik-Wiki/BlockMap
    cd BlockMap
    ./gradlew regenerate
    ./gradlew run2
    ./gradlew run

Sorry about misreading your issue, some details went under between stack traces due to formatting.

**Comment by rkiddy** [comment]
If I only had java8, would I have been able to run after doing a "./gradlew regenerate"?

Hm. I did not need to install java11. I had obtained java12 as the default choice out of brew, and that worked.

As per your suggestion, I was able to do:

      git clone https://github.com/Minecraft-Technik-Wiki/BlockMap
      cd BlockMap
      ./gradlew regenerate
      ./gradlew run2

and it was all good!

And I have:

     $ java -version
     openjdk version "12.0.1" 2019-04-16
     OpenJDK Runtime Environment (build 12.0.1+12)
     OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
