### ISSUE TITLE
Error: cannot access class com.sun.javafx.util.Utils

### ISSUE THREAD

**Issue by Mfweb** [Minecraft-Technik-Wiki/BlockMap#26]
## Environment info

- **BlockMap version**: `1.3.0`
- **Java version**: `Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)`
- **Operating system**: `Windows 10 1903` 

## Description

command: `java --module-path "C:\Program Files\Java\javafx-sdk-11.0.2\lib" --add-modules=javafx.controls,javafx.swing -jar .\BlockMap-1.3.0.jar`
error message:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
19-06-10 04:17:40:790 FATAL GuiMain [46] - Cannot start BlockMap
java.lang.IllegalAccessError: class com.sun.javafx.fxml.FXMLLoaderHelper (in unnamed module @0x6e3039d9) cannot access class com.sun.javafx.util.Utils (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.util to unnamed module @0x6e3039d9
        at com.sun.javafx.fxml.FXMLLoaderHelper.<clinit>(FXMLLoaderHelper.java:38) ~[BlockMap-1.3.0.jar:?]
        at javafx.fxml.FXMLLoader.<clinit>(FXMLLoader.java:2056) ~[BlockMap-1.3.0.jar:?]
        at de.piegames.blockmap.guistandalone.GuiMain.start(GuiMain.java:34) ~[BlockMap-1.3.0.jar:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx.graphics.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx.graphics.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Steps to reproduce

1. Open PowerShell
2. Run command.

### Actual result
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
19-06-10 04:17:40:790 FATAL GuiMain [46] - Cannot start BlockMap
java.lang.IllegalAccessError: class com.sun.javafx.fxml.FXMLLoaderHelper (in unnamed module @0x6e3039d9) cannot access class com.sun.javafx.util.Utils (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.util to unnamed module @0x6e3039d9
        at com.sun.javafx.fxml.FXMLLoaderHelper.<clinit>(FXMLLoaderHelper.java:38) ~[BlockMap-1.3.0.jar:?]
        at javafx.fxml.FXMLLoader.<clinit>(FXMLLoader.java:2056) ~[BlockMap-1.3.0.jar:?]
        at de.piegames.blockmap.guistandalone.GuiMain.start(GuiMain.java:34) ~[BlockMap-1.3.0.jar:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx.graphics.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx.graphics.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Expected result:
Replace me

**Comment by piegamesde** [comment]
Please try adding the module `javafx.fxml` and maybe also `javafx.graphics`.

You can also try this workaround:
```
git clone https://github.com/Minecraft-Technik-Wiki/BlockMap
cd BlockMap
./gradlew regenerate
./gradlew run2
```

**Comment by Mfweb** [comment]
The second method works fine

**Comment by piegamesde** [comment]
Okay, I'll add it to the documentation.
