### ISSUE TITLE
Error: NoSuchElementException: No value present

### ISSUE THREAD

**Issue by RDPrandomname** [Minecraft-Technik-Wiki/BlockMap#28]
**Command used:** `sudo java -jar BlockMap-1.4.0.jar -v render -l --create-tile-html --min-X=15000 --max-X=15000 --min-Z=15000 --max-Z=15000 -o="/var/www/html/render/topdown" "/home/mc/world name/region"`

Result: 

```WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/home/mc/render/BlockMap-1.4.0.jar) to constructor java.util.Optional()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
19-06-23 00:38:09 INFO  PostProcessing [34] - Writing HTML tiles...
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (de.piegames.blockmap.standalone.CommandLineMain$CommandRender@6c0d7c83): java.util.NoSuchElementException: No value present
        at picocli.CommandLine.execute(CommandLine.java:1051)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:1344)
        at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:209)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.OptionalInt.getAsInt(OptionalInt.java:128)
        at de.piegames.blockmap.standalone.PostProcessing.createTileHtml(PostProcessing.java:53)
        at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:181)
        at picocli.CommandLine.execute(CommandLine.java:1043)
        ... 7 more
```
Currently trying to run version 1.4.0 on a Debian server.

**Comment by piegamesde** [comment]
This seems to be because the set of regions you are rendering is empty. Check your bounds: `--min-X=15000 --max-X=15000 --min-Z=15000 --max-Z=15000` I assume the min values should be negative?

I'll add a better error message.
