### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by bugmancx** [Minecraft-Technik-Wiki/BlockMap#29]
Under the Java 12 JDK I get the following error while trying to run this app. I am running this on Windows 10 build 1903.

ERROR FOLLOWS:

```
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

- `java version "12.0.2" 2019-07-16`
- `Java(TM) SE Runtime Environment (build 12.0.2+10)`
- `Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)`

**Comment by piegamesde** [comment]
What hardware are you on? JavaFX is looking for some hardware acceleration but it can't find any.

I don't think this is a BlockMap specific issue though, but rather your general Java/JavaFX configuration may be wrong. To test this, you could try out some other JavaFX applications and see if they don't work either.

**Comment by tbyronb** [comment]
Added a few Windows specific packages to the jar and things seem to be working.
com.sun.prism.d3d
com.sun.glass.ui.win
com.sun.scenario.effect.impl.hw.d3d


Prism pipeline name = com.sun.prism.d3d.D3DPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.d3d.D3DPipeline
java.lang.ClassNotFoundException: com.sun.prism.d3d.D3DPipeline
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:835)
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: no prism_sw in java.library.path:

**Comment by piegamesde** [comment]
Does this mean that BlockMap currently doesn't run out of the box on Windows?

**Comment by tbyronb** [comment]
It did not for me but I also have a dozen java versions and probably conflicting things in my path. Believe you need to add the platform specific JavaFX dependencies to the archive but for all I know the failure of the fallback to the SWPipeline not working is specific to my setup.  

Also required Java 12+ not 11+.

**Comment by piegamesde** [comment]
Thanks for pointing out the wrong Java version.

Can you please try out to run it [from Gradle](https://github.com/Minecraft-Technik-Wiki/BlockMap#compile-it-yourself)? Maybe I'll need to add platform dependent releases (sigh).

**Comment by tbyronb** [comment]
No issue if built locally, looks like it's just the JavaFX platform specific stuff. 

My fat jar had these additions:
com.sun.glass.ui.win
com.sun.prism.d3d
com.sun.scenario.effect.impl.hw.d3d

and did not contain these:
com.sun.glass.ui.gtk
com.sun.prism.es2
com.sun.scenario.effect.impl.es2

**Comment by piegamesde** [comment]
Thank you very much, I'll look further into it.

**Comment by piegamesde** [comment]
Please have a look at `1.5.0`, we now have Windows releases.

**Comment by tbyronb** [comment]
Looks good, launched without error.
