### ISSUE TITLE
About Pane not found

### ISSUE THREAD

**Issue by tbyronb** [Minecraft-Technik-Wiki/BlockMap#30]
## Environment info

- **BlockMap version**: `1.5.0`
- **Java version**: `12.0.2`
- **Operating system**: `Windows 10` 

## Description

Error dialog on navigation to Help->About. 
A single "guistandalone" didn't get split to "gui.standalone" in /BlockMap-gui/src/main/resources/de/piegames/blockmap/gui/standalone/about/dependency.fxml

## Steps to reproduce

Navigate to Help->About.

## Debug log

```
javafx.fxml.LoadException: de.piegames.blockmap.guistandalone.about.DependencyPane is not a valid type.
file:/C:/Users/lincoln/Downloads/BlockMap-gui-1.5.0-windows-10.jar!/de/piegames/blockmap/gui/standalone/about/dependency.fxml:21
    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2621) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader$RootElement.constructValue(FXMLLoader.java:1314) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at de.piegames.blockmap.gui.standalone.about.DependencyPane.<init>(DependencyPane.java:27) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at de.piegames.blockmap.gui.standalone.about.AboutDialog.<init>(AboutDialog.java:72) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at de.piegames.blockmap.gui.standalone.GuiController.showAbout(GuiController.java:438) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
    at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
    at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.event.Event.fireEvent(Event.java:198) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.event.Event.fireEvent(Event.java:198) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3862) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.scene.Scene.processMouseEvent(Scene.java:1849) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2590) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at java.security.AccessController.doPrivileged(AccessController.java:389) ~[?:?]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.glass.ui.View.notifyMouse(View.java:942) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[BlockMap-gui-1.5.0-windows-10.jar:?]
    at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by piegamesde** [comment]
That's embarrassing. I knew I'd forget one or two locations …
