### ISSUE TITLE
Unsupported compression type, must be between 0 and 2

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#33]
I am getting this error on one of my maps, others work fine.

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (de.piegames.blockmap.standalone.CommandLineMain$CommandRender@59b38691): java.lang.IllegalArgumentException: Unsupported compression type, must be between 0 and 2 (inclusive)
	at picocli.CommandLine.execute(CommandLine.java:1051)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1344)
	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:199)
Caused by: java.lang.IllegalArgumentException: Unsupported compression type, must be between 0 and 2 (inclusive)
	at com.flowpowered.nbt.stream.NBTInputStream.<init>(NBTInputStream.java:120)
	at com.flowpowered.nbt.stream.NBTInputStream.<init>(NBTInputStream.java:92)
	at com.flowpowered.nbt.regionfile.Chunk.getInputStream(Chunk.java:192)
	at com.flowpowered.nbt.regionfile.Chunk.readTag(Chunk.java:199)
	at de.piegames.blockmap.renderer.RegionRenderer.renderRaw(RegionRenderer.java:113)
	at de.piegames.blockmap.renderer.RegionRenderer.render(RegionRenderer.java:56)
	at de.piegames.blockmap.world.RegionFolder$WorldRegionFolder.render(RegionFolder.java:150)
	at de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.render(RegionFolder.java:395)
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:156)
	at picocli.CommandLine.execute(CommandLine.java:1043)
	... 7 more 
```

**Comment by piegamesde** [comment]
Can you reproduce it with your map? If so, can you please mail me the affected world? Which version of  BlockMap/Java/Minecraft are you using?

**Comment by uncovery** [comment]
Yeah sorry, this was maybe a bit hasty. It seems that the issue is not reproducible.
