### ISSUE TITLE
Generating HTML file fails

### ISSUE THREAD

**Issue by jedenastka** [Minecraft-Technik-Wiki/BlockMap#36]
## Environment info
- **BlockMap version**: `1.6.1`
- **Java version**:
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
- **Operating system**:
```
~ $ uname -a
Linux pecet 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
~ $ cat /etc/debian_version 
bullseye/sid
```

## Description
I can't get the HTML map to generate propertly, it fails with an error.

## Steps to reproduce
```
jdk-13.0.2/bin/java -jar Pobrane/BlockMap-cli-1.6.1.jar -v render -l --create-tile-html -d OVERWORLD -o a Minecraft/Zapisy/Lody
```

### Actual result
```
~ $ cat a/tiles.html 
<html><head>
<link rel="stylesheet" type="text/css" href="tiles.css"/>
</head><body>
<div style="height: 18944px">%
~ $
```

### Expected result:
Working map in HTML file.

## Debug log
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/home/grzesiek11/Pobrane/BlockMap-cli-1.6.1.jar) to field java.util.Optional.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20-03-10 16:21:57 INFO  PostProcessing [34] - Writing HTML tiles...
java.lang.NullPointerException
        at de.piegames.blockmap.world.RegionFolder$LocalRegionFolder.getPath(RegionFolder.java:315)
        at de.piegames.blockmap.standalone.PostProcessing.createTileHtml(PostProcessing.java:73)
        at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:202)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
        at picocli.CommandLine.execute(CommandLine.java:1864)
        at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:210)
```

**Comment by piegamesde** [comment]
Thanks for reporting. There was a bug when rendering non-rectangular worlds. Please try out the latest master, I'll do a release if you confirm that this resolves the issue for you.

**Comment by jedenastka** [comment]
Yeah, it works when compiled from master.
