### ISSUE TITLE
Rendering stops with State unstable=false does not exist

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#5]
18-11-09 15:11:28:542 WARN  RegionRenderer [211] - Skipping chunk
java.lang.IllegalArgumentException: State unstable=false does not exist
        at de.piegames.blockmap.renderer.BlockState.valueOf(BlockState.java:317) ~[BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.renderer.RegionRenderer.parseBlockState(RegionRenderer.java:260) ~[BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.renderer.RegionRenderer.lambda$renderSection$3(RegionRenderer.java:234) ~[BlockMap-1.1.1.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_191]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_191]
        at de.piegames.blockmap.renderer.RegionRenderer.renderSection(RegionRenderer.java:235) ~[BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.renderer.RegionRenderer.renderRaw(RegionRenderer.java:172) [BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.renderer.RegionRenderer.render(RegionRenderer.java:43) [BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:156) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:858) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.access$700(CommandLine.java:104) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1035) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1003) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:911) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1194) [BlockMap-1.1.1.jar:?]
        at picocli.CommandLine.parseWithHandler(CommandLine.java:1133) [BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:202) [BlockMap-1.1.1.jar:?]
Caused by: java.lang.IllegalArgumentException: No enum constant de.piegames.blockmap.renderer.BlockState.UNSTABLE_FALSE
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_191]
        at de.piegames.blockmap.renderer.BlockState.valueOf(BlockState.java:10) ~[BlockMap-1.1.1.jar:?]
        at de.piegames.blockmap.renderer.BlockState.valueOf(BlockState.java:315) ~[BlockMap-1.1.1.jar:?]
        ... 22 more

**Comment by piegamesde** [comment]
The block state `unstable` seems to have been added to 1.13.1, so it is currently not included in the latest BlockMap release. I already fixed this, but I can't push the changes yet since it currently breaks the build due to some complicated things.

**Comment by uncovery** [comment]
Yeah it seems I could fix this now by updating all the chunks to 1.13
