### ISSUE TITLE
Rendering fails 1.16.1

### ISSUE THREAD

**Issue by unsupervisednn** [Minecraft-Technik-Wiki/BlockMap#55]
Command 

## Environment info

- **BlockMap version**: `2.1.0`
- **Java version**: `java -version`
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
```
- **Operating system**: `Replace me` 
```
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
macOS 10.15.3 Catalina
```

## Description
Can't finish render any dimension without errors like the following:
```
20-07-23 15:15:03 WARN  LevelMetadata [501] - Could not access map map_143.dat
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at de.piegames.blockmap.world.LevelMetadata.loadFromWorld(LevelMetadata.java:496) [blockmap.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain$CommandServer.call(CommandLineMain.java:379) [blockmap.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain$CommandServer.call(CommandLineMain.java:277) [blockmap.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743) [blockmap.jar:?]
	at picocli.CommandLine.access$900(CommandLine.java:145) [blockmap.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101) [blockmap.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068) [blockmap.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935) [blockmap.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:1864) [blockmap.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain.mainWithoutQuit(CommandLineMain.java:415) [blockmap.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:419) [blockmap.jar:?]
```

```
20-07-23 15:15:03 WARN  LevelMetadata [454] - r.2.-10.mca is empty?!
20-07-23 15:15:03 WARN  LevelMetadata [454] - r.1.-10.mca is empty?!
```

```

```
## Steps to reproduce
```json
{
	"output dir": "./rendered-web",
	"server": {
		"server name": "Minecraaaaaaft",
		"server description": "The best server in the world",
		"server address": "127.0.0.1",
		"max players": 5
	},
	"worlds": [
		{
			"name": "End",
			"input dir": "../lambdacraft-server-1.16/world",
			"dimension": "END",
			"force": false
		}
	]
}
```
1. `java -jar blockmap-2.1.0.jar render-many config.json`

**Comment by unsupervisednn** [comment]
Sample region that it said was empty
[r.2.-10.mca.zip](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/4966538/r.2.-10.mca.zip)

**Comment by piegamesde** [comment]
The map error should not be critical to the rendering process. Apart from that, I fixed that error yesterday, it's the latest commit on the master branch.

About the empty region warning, as the log comes from `LevelMetadata`, it's probably about `poi/r.2.-10.mca` instead of `region/r.2.-10.mca`. I'll improve the log messages.

**Comment by piegamesde** [comment]
Closing now as the fix has been released.
