### ISSUE TITLE
Failed to render Nether/End with NullPointerException

### ISSUE THREAD

**Issue by awdavis** [Minecraft-Technik-Wiki/BlockMap#77]
## Environment info

- **BlockMap version**: `2.4.1`
- **Java version**:
  ```
  java version "18" 2022-03-22
  Java(TM) SE Runtime Environment (build 18+36-2087)
  Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
  ```
- **Operating system**: `Windows 10 Pro Build 19044`

## Description
Unable to render nether/end maps on relatively new Aternos server.

## Steps to reproduce
1. Download `world` directory from [Aternos](https://aternos.org/files/) and save it at `D:/Minecraft/aternos-world`
2. Open Command Prompt
3. Run `"C:/Program Files/Java/jdk-18/bin/java.exe" -jar "D:/Minecraft/BlockMap/BlockMap-cli-2.4.1.jar" --verbose render --output="D:/Minecraft/map-output/end" --dimension=END --create-big-image "D:/Minecraft/aternos-world"`
4. Inspect command output

### Actual result
The command fails to produce an image and produces error output.

### Expected result:
The command produces an image as expected.

### Troubleshooting
* The command does not work for either rendering tiles or a big image on The End
* The command does not work for either rendering tiles or a big image on the Nether
* The command does work as expected for rendering tiles and a big image for the Overworld
* Some but not all of the generated tile images appear empty, for each of the above dimensions ![preview of end tiles](https://user-images.githubusercontent.com/2943788/161464876-d505705b-3f6a-4f42-b1cb-4e7e299a28f7.png)

### Full output
[test_output.txt](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/8406285/test_output.txt)
### Selected output
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
22-04-03 19:23:04 INFO  RegionRenderer [58] - Rendering region file -2 -3
22-04-03 19:23:04 WARN  ChunkRenderer_1_18 [249] - Failed to render chunk (22, 0) section -1. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: Cannot invoke "de.piegames.nbt.CompoundMap.get(Object)" because "section" is null
	at de.piegames.blockmap.renderer.ChunkRenderer_1_18.renderSection(ChunkRenderer_1_18.java:297) ~[BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.renderer.ChunkRenderer_1_18.renderChunk(ChunkRenderer_1_18.java:191) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.renderer.RegionRenderer.renderRaw(RegionRenderer.java:149) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.renderer.RegionRenderer.render(RegionRenderer.java:61) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.world.RegionFolder$WorldRegionFolder.render(RegionFolder.java:179) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.render(RegionFolder.java:467) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:249) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:113) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine.access$1300(CommandLine.java:145) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) [BlockMap-cli-2.4.1.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2078) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain.mainWithoutQuit(CommandLineMain.java:399) [BlockMap-cli-2.4.1.jar:?]
	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:403) [BlockMap-cli-2.4.1.jar:?]
...
ava.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @21213b92
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getDelegateAdapter(Gson.java:572)
	at io.gsonfire.gson.HooksTypeAdapterFactory.create(HooksTypeAdapterFactory.java:23)
	at com.google.gson.Gson.getDelegateAdapter(Gson.java:572)
	at io.gsonfire.gson.WrapTypeAdapterFactory.create(WrapTypeAdapterFactory.java:26)
	at com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getDelegateAdapter(Gson.java:572)
	at io.gsonfire.gson.HooksTypeAdapterFactory.create(HooksTypeAdapterFactory.java:23)
	at com.google.gson.Gson.getDelegateAdapter(Gson.java:572)
	at io.gsonfire.gson.TypeSelectorTypeAdapterFactory$TypeSelectorTypeAdapter.write(TypeSelectorTypeAdapterFactory.java:58)
	at io.gsonfire.gson.NullableTypeAdapter.write(NullableTypeAdapter.java:26)
	at io.gsonfire.util.JsonUtils.toJsonTree(JsonUtils.java:54)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:42)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at io.gsonfire.util.JsonUtils.toJsonTree(JsonUtils.java:54)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:42)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at io.gsonfire.postprocessors.methodinvoker.MethodInvokerPostProcessor.postSerialize(MethodInvokerPostProcessor.java:82)
	at io.gsonfire.gson.HooksTypeAdapter.runPostSerialize(HooksTypeAdapter.java:72)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:49)
	at io.gsonfire.util.JsonUtils.toJsonTree(JsonUtils.java:54)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:42)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at io.gsonfire.util.JsonUtils.toJsonTree(JsonUtils.java:54)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:42)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at io.gsonfire.util.JsonUtils.toJsonTree(JsonUtils.java:54)
	at io.gsonfire.gson.HooksTypeAdapter.write(HooksTypeAdapter.java:42)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJson(Gson.java:714)
	at com.google.gson.Gson.toJson(Gson.java:689)
	at de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.save(RegionFolder.java:536)
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:262)
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:113)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at de.piegames.blockmap.standalone.CommandLineMain.mainWithoutQuit(CommandLineMain.java:399)
	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:403)
```

**Comment by piegamesde** [comment]
I am sorry, but the download link requires me to log in. I suspect that it is bound to your files from your account, so it wouldn't work either way. If you don't mind, please send me the failing file (`r.-2.-3.mca` in the End folder).

**Comment by awdavis** [comment]
Attached please find the r.-2.-3.mca file in the DIM1 directory.

**Comment by awdavis** [comment]
GitHub won't allow uploading .mca files, so here it is in zip format: [r.-2.-3.zip](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/8408827/r.-2.-3.zip)

**Comment by piegamesde** [comment]
I just pushed a potential fix to the `develop` branch, please check it out

**Comment by awdavis** [comment]
Thanks, I built the CLI jar from the develop branch and confirmed that my original CLI commands run to completion and no longer produce any errors, so this seems like an improvement.

However, by building manually, I was able to run the GUI for the first time ever (since I am on Windows), and based on the pins, it still seems to note a bunch of corrupt chunks in the End and in the Nether dimensions only. It seems potentially related to the original issue.

End example here:
![image](https://user-images.githubusercontent.com/2943788/164951291-8ce247c1-931b-43e0-a5ad-746d4e8c635a.png)

```
java.lang.NullPointerException: Cannot read field "isTranslucent" because "colorData" is null
	at de.piegames.blockmap.renderer.ChunkRenderer_1_18.renderChunk(ChunkRenderer_1_18.java:274)
	at de.piegames.blockmap.renderer.RegionRenderer.renderRaw(RegionRenderer.java:149)
	at de.piegames.blockmap.renderer.RegionRenderer.render(RegionRenderer.java:61)
	at de.piegames.blockmap.world.RegionFolder$WorldRegionFolder.render(RegionFolder.java:179)
	at de.piegames.blockmap.gui.RenderedMap.run(RenderedMap.java:97)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Nether example here:
![image](https://user-images.githubusercontent.com/2943788/164951366-1408171a-b944-40bc-82a9-bde8ef1544ba.png)

```
java.lang.NullPointerException
```

This makes me think something still isn't quite right...

For comparison, here is a rendering of the Overworld:
![image](https://user-images.githubusercontent.com/2943788/164951413-b554bfe6-e152-49d5-a461-186fbcb598dc.png)

**Comment by awdavis** [comment]
In the released GUI, there are lots of "Corrupt chunks" in the Nether dimension:
![image](https://user-images.githubusercontent.com/2943788/164959821-8cc7b280-250a-4545-b746-605f40f36e9c.png)

In the develop branch GUI, those are instead shown as "Unfinished chunks" in the Nether dimension:
![image](https://user-images.githubusercontent.com/2943788/164959839-f837fdd5-72cb-4bcf-a1df-b450a7b4705b.png)

In the released GUI, the End has many "Corrupt chunks" as well:
![image](https://user-images.githubusercontent.com/2943788/164960016-c0c156db-63b7-48fb-851e-fc16cc2ccc9c.png)


In the develop branch GUI, the End only has a few "Unfinished chunks" and doesn't show any "Corrupt chunks." It also only seems to display the "End city" pins that are near an unfinished chunk pin, and the rest do not appear for some reason.
![image](https://user-images.githubusercontent.com/2943788/164960068-9968e815-07b2-49bb-a256-59c8cdde3bd1.png)

**Comment by piegamesde** [comment]
Thank you for the information. My fix does not appear to work as hoped. I have pushed a second attempt onto the `developer` branch, please try it out and see if it improves things.

**Comment by awdavis** [comment]
I downloaded the new version and ran `gradle regenerate` and `gradle previewRelease`, like I did last time. Here are the results from the GUI:
![image](https://user-images.githubusercontent.com/2943788/164969535-15b72512-ee5c-4ddc-a5aa-0095c3eaeb02.png)

![image](https://user-images.githubusercontent.com/2943788/164969602-139bd748-12c6-4f8e-ab46-fec77aa2b73d.png)

I am not sure what changes I am supposed to be looking for, but I don't see any obvious difference from since previous commit. I still see the same number of "Unfinished chunks" pins as before.

**Comment by piegamesde** [comment]
Try walking to those "unfinished" chunks in Minecraft. If they render fine afterwards, nothing's wrong. Otherwise, please send me a region file with them so that I may take a look.

**Comment by awdavis** [comment]
I walked around in the Nether and rerendered, and it doesn't seem to show any unfinished chunks in the area where I walked, so I'll consider that to be a good sign! (Unfinished chunk pins are off, but the corrupt chunk pins are on.)

before: 
![image](https://user-images.githubusercontent.com/2943788/165032079-7db0b744-cbde-486f-a2cd-a6926e6674b4.png)

after: 
![image](https://user-images.githubusercontent.com/2943788/165032103-747dc574-18bf-498f-bbf0-24221905ad8c.png)
