### ISSUE TITLE
run fails: Did not find internal color map default

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#8]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (de.piegames.blockmap.standalone.CommandLineMain$CommandRender@433d61fb): java.lang.IllegalArgumentException: Did not find internal color map default
        at picocli.CommandLine.execute(CommandLine.java:1051)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:1344)
        at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:208)
Caused by: java.lang.IllegalArgumentException: Did not find internal color map default
        at de.piegames.blockmap.color.BlockColorMap.loadInternal(BlockColorMap.java:154)
        at de.piegames.blockmap.color.BlockColorMap$InternalColorMap.getColorMap(BlockColorMap.java:32)
        at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.run(CommandLineMain.java:125)
        at picocli.CommandLine.execute(CommandLine.java:1043)
        ... 7 more
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at de.piegames.blockmap.color.BlockColorMap.loadInternal(BlockColorMap.java:152)
        ... 10 more

I assume I have to use BlockMap/BlockMap-standalone/build/libs/BlockMap-1.1.1.jar ?

**Comment by piegamesde** [comment]
Normally, running the jar from `gradle github` should work as well as directly starting it with `gradle run`. So either the required resources did not get generated, or they didn't get copied into the final jar.

**Comment by uncovery** [comment]
ok that worked now, thanks!

**Comment by piegamesde** [comment]
They should be in the top level folder of the jar, and are called `block-colors-*.json`. They should also appear in `BlockMap-core/src/main/generated-resources` which links to `BlockMap-internal/build/generated-resources/core-main/` and will be copied to `/build/resources` at runtime by Gradle.

**Comment by uncovery** [comment]
also fixed with the latest release
